name: "Groovy Script Runner with Declarative Inputs"
description: "Run a Groovy script with declarative inputs like Maven version"
author: "Your Name"
inputs:
  build-profile:
    description: "The build profile to use"
    required: false
    default: "default"
  additional-args:
    description: "Additional arguments for the Groovy script"
    required: false
    default: ""
outputs:
  result:
    description: "The result from the Groovy script"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.build-profile }}"
    - "${{ inputs.additional-args }}"
