name: Workflow Dispatch
on:
  workflow_dispatch:
jobs:
  run-groovy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Custom Groovy Action
        uses: ./ # Local action path
        with:
          mvn-version: "3.8.6"
          build-profile: "release"
          additional-args: "-DskipTests"
