name: Workflow Dispatch
on:
  workflow_dispatch:
jobs:
  run-groovy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Custom Groovy Action
        uses:  dev-sha-ops/global-pipeline-library/.github/workflows/action.yml@main
        with:
          input1: "-DskipTests1"
          input2: "-DskipTests2"
          input3: "-DskipTests3"